# Site Settings
title: "Xinyu Zhang"
description: "Ph.D. Student in Communication Studies"
url: "https://bluexinyu.github.io"
baseurl: ""
repository: "bluexinyu/bluexinyu.github.io"

# Build settings
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Site Author
author:
  name: "Xinyu Zhang"
  avatar: "/assets/images/profile.jpg"
  bio: "Ph.D Student<br>Department of Communication<br>College of Communication Arts and Sciences<br>Michigan State University"
  location: "East Lansing, MI"
  email: "zxinyu@msu.edu"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:zxinyu@msu.edu"

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Navigation
include: ["_pages"]

# Pagination
paginate: 5
paginate_path: /page:num/

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
