remote_theme: "mmistakes/minimal-mistakes@4.27.3"

title: "Xinyu Zhang"
name: "Xinyu Zhang" 
description: "Ph.D. Student in Communication Studies"
url: "https://bluexinyu.github.io"

# 正确的academicons CDN
head_scripts:
  - https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css

author:
  name: "Xinyu Zhang"
  avatar: "/assets/images/profile.jpg"
  bio: |
    <span style="font-size: 0.9em; font-weight: 500;">Ph.D Student</span><br>
    <span style="font-size: 0.8em;">Department of Communication</span><br>
    <span style="font-size: 0.8em;">College of Communication Arts and Sciences</span><br>
    <span style="font-size: 0.8em;">Michigan State University</span><br>
    <span style="font-size: 0.75em; color: #666;">Email: zxinyu@msu.edu</span>
  location: "East Lansing, Michigan"
  links:
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=LxyHOE8AAAAJ&hl=en"
    - label: "ResearchGate"
      icon: "ai ai-researchgate"
      url: "https://www.researchgate.net/profile/Xinyu-Zhang-293?ev=hdr_xprf"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://x.com/Xinyu__Zhang"
    - label: "Instagram" 
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/bea_xinyu/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bluexinyu"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single  
      author_profile: true

minimal_mistakes_skin: "default"
paginate: 5
paginate_path: /page:num/
