remote_theme: "mmistakes/minimal-mistakes@4.27.3"

title: "Xinyu Zhang"
name: "Xinyu Zhang" 
description: "Ph.D. Student in Communication Studies"
url: "https://bluexinyu.github.io"

author:
  name: "Xinyu Zhang"
  avatar: "https://via.placeholder.com/300x300/4472C4/ffffff?text=XZ"
  bio: |
    **Ph.D. Student**  
    Department of Communication Studies  
    Michigan State University
    
    **Email:** zxinyu@msu.edu
  location: "East Lansing, Michigan"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bluexinyu"
    - label: "Instagram" 
      icon: "fab fa-fw fa-instagram"
      url: "#"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single  
      author_profile: true

minimal_mistakes_skin: "default"
paginate: 6
